<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Rethrowing an exception in JavaScript | </title>
		
		<link rel="stylesheet" href="../../../../../tore/@/fonts/listΣ.css?v=1">
<link rel="stylesheet" href="../../../../../tore/layd/deff/&/aefb44b7dac371a3860e9079298a950e.ructΣ.css">
<link rel="stylesheet" href="../../../../../tore/&/2290bf7aeadc4261337d6f570a3cf0c5.apprΣ.css">

<script src="../../../../../tore/&/77748427269d1c81490f5acb6ce46fc1.apprΣ.js" defer></script>


<meta name="yandex-verification" content="00eb45b7559e5c68">
<meta name="google-site-verification" content="Af0TM2OrwIEtjoQXxYz2-1C-21E1m7DB23_kWpE9sLg">
<meta name="viewport" content="width=device-width, initial-scale=1.0">		
		<meta name="description" content="In this lesson, we will learn how to rethrow exceptions in JavaScript.">
		<link rel="shortcut icon" type="image/x-icon" href="../../../../../favicon.ico">
	</head>
	<body id="top" data-gq="D">
		<div data-r="ruct/wrap">
			<header>
				<div data-r="ruct/topp">
	<div data-r="topp/left">
		<div data-w="nict/logo">
	<img data-e="img" data-x src="" alt="">
</div>	</div>
	<div data-r="topp/righ">
		offline version v3	</div>
	<div data-r="topp/cent">
		<br><br>	</div>
</div>								
				<div data-r="ruct/navi">
					<div data-w="nict/over">
			<span data-e="hash" data-x>⊗jsSpExcPrb</span>
				<span data-e="lofo" data-x>150 of 281</span>
				<a href="../../../../../en/javascript/book/supreme.html" data-e="link" data-x>menu</a>
	</div>					<nav data-w="nict/mainmenu">
	<section data-e="main" data-x data-gm-acte="T">
		<span data-q-href="/en/markup/" data-e="open" data-x data-m-targ="markup">Markup</span>
		<span data-q-href="/en/javascript/" data-e="open" data-x data-m-targ="javascript">JavaScript</span>
	</section>
	
	<section data-e="subb" data-x data-gm-acte="F" data-m-tabb="markup">
		<a href="../../../../../en/markup/manual/html.html">HTML manual</a>
		<a href="../../../../../en/markup/manual/css.html">CSS manual</a>
	</section>
	
	<section data-e="subb" data-x data-gm-acte="F" data-m-tabb="javascript">
		<a href="../../../../../en/javascript/book/prime.html">Prime book</a>
		<a href="../../../../../en/javascript/book/practice.html">Practice book</a>
		<a href="../../../../../en/javascript/book/supreme.html">Supreme book</a>
		<a href="../../../../../en/javascript/manual.html">Manual</a>
	</section>
</nav>									</div>
			</header>
			<main>
				<div data-w="nict/hett">
	<h1>Rethrowing an exception in JavaScript</h1>
</div>				<div data-p="cont/pane">
<p>
	Let's consider the <code data-gs="comd/c" data-x>catch</code>-block of 
	the task with product JSON:
</p>
<div data-p="bock/pane">
	<code data-w="bock/code" data-lo="high" data-m-lang="javascript">catch (error) {
	if (error.name == 'SyntaxError') {
		alert('Invalid JSON of the product');
	} else if (error.name == 'ProductCostError') {
		alert('Product has no price or amount');
	}
}</code>
</div>
<p>
	As you can see, we catch the two exceptions 
	we planned and somehow react to it. But what 
	happens if an exception of a different type 
	that we didn't expect occurs? In this case, 
	it will also fall into a <code data-gs="comd/c" data-x>catch</code>-block, 
	but there will be no reaction to this, since 
	the exception with a different type simply 
	will not fall into any of our IFs.
</p>
<p>
	When I say that there will be no reaction, 
	I mean that there really is none: there will 
	not even be an error thrown into the console. 
	Our code just silently won't work.
</p>
<p>
	Therefore, there is the following rule: your 
	code should only catch exceptions that it 
	knows how to handle. If the exception is not 
	known, then it must be <dfn data-gs="comd/d" data-x>rethrow</dfn> further 
	with <code data-gs="comd/c" data-x>throw</code>. In this case, someone more 
	knowledgeable will catch it above, or an 
	exception will be thrown into the console 
	as an error.
</p>
<p>
	Let's fix our code:
</p>
<div data-p="bock/pane">
	<code data-w="bock/code" data-lo="high" data-m-lang="javascript">catch (error) {
	if (error.name == 'SyntaxError') {
		alert('Invalid JSON of the product');
	} else if (error.name == 'ProductCostError') {
		alert('Product has no price or amount');
	} else {
		throw error; // rethrow the exception further
	}
}</code>
</div>
<div data-w="cont/task">
	<p>
		Given the following code:
	</p>
	<div data-p="bock/pane">
		<code data-w="bock/code" data-lo="high" data-m-lang="javascript">try {
	let arr = JSON.parse(json);

	for (let i = 0; i &lt; arr.length; i++) {
		localStorage.setItem(i, arr[i]);
	}
} catch (error) {
	if (error.name == 'QuotaExceededError') {
		alert('ran out of storage space');
	}
	
	if (error.name == 'SyntaxError') {
		alert('invalid json');
	}
}</code>
	</div>
	<p>
		What's wrong with this code? Fix it 
		for a better one.
	</p>
</div>
</div>			</main>
				<div data-w="nict/nebr">
					<a href="../../../../../en/javascript/book/supreme/exceptions/json-structure-example.html" data-e="prev" data-x>
				<span data-e="arow" data-x>&larr;</span>
			</a>
							<a href="../../../../../en/javascript/book/supreme/asynchrony/intro.html" data-e="next" data-x>
				<span data-e="arow" data-x>&rarr;</span>
			</a>
			</div>
			<footer data-w="ruct/foot">
				<div data-w="nict/finf">
	<span data-e="text" data-x>
		Trepachev Dmitry &copy; 2012-2024	</span>
	<br>
	<a data-e="link" data-x href="https://t.me/trepachev_dmitry">t.me/trepachev_dmitry</a>
</div>							</footer>
			<div data-w="nict/jump">
	<a href="#top"><span>&uarr;</span></a>
</div>			<div data-w="nict/lagr">
	<a href="../../../../../en/javascript/book/supreme/exceptions/probing.html" data-m-curr="T">en</a><a href="../../../../../ru/javascript/book/supreme/exceptions/probing.html" data-m-curr="F">ru</a></div>					</div>
		
		<script src="../../../../../tore/@/metrikaΣ.js?v=1"></script>	</body>
</html>