<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Exceptions within promises in JavaScript | </title>
		
		<link rel="stylesheet" href="../../../../../tore/@/fonts/listΣ.css?v=1">
<link rel="stylesheet" href="../../../../../tore/layd/deff/&/aefb44b7dac371a3860e9079298a950e.ructΣ.css">
<link rel="stylesheet" href="../../../../../tore/&/2290bf7aeadc4261337d6f570a3cf0c5.apprΣ.css">

<script src="../../../../../tore/&/77748427269d1c81490f5acb6ce46fc1.apprΣ.js" defer></script>


<meta name="yandex-verification" content="00eb45b7559e5c68">
<meta name="google-site-verification" content="Af0TM2OrwIEtjoQXxYz2-1C-21E1m7DB23_kWpE9sLg">
<meta name="viewport" content="width=device-width, initial-scale=1.0">		
		<meta name="description" content="In this lesson, we will learn how to handle exceptions that happen within a promise in JavaScript.">
		<link rel="shortcut icon" type="image/x-icon" href="../../../../../favicon.ico">
	</head>
	<body id="top" data-gq="D">
		<div data-r="ruct/wrap">
			<header>
				<div data-r="ruct/topp">
	<div data-r="topp/left">
		<div data-w="nict/logo">
	<img data-e="img" data-x src="" alt="">
</div>	</div>
	<div data-r="topp/righ">
		offline version v3	</div>
	<div data-r="topp/cent">
		<br><br>	</div>
</div>								
				<div data-r="ruct/navi">
					<div data-w="nict/over">
			<span data-e="hash" data-x>⊗jsSpPrmEx</span>
				<span data-e="lofo" data-x>163 of 281</span>
				<a href="../../../../../en/javascript/book/supreme.html" data-e="link" data-x>menu</a>
	</div>					<nav data-w="nict/mainmenu">
	<section data-e="main" data-x data-gm-acte="T">
		<span data-q-href="/en/markup/" data-e="open" data-x data-m-targ="markup">Markup</span>
		<span data-q-href="/en/javascript/" data-e="open" data-x data-m-targ="javascript">JavaScript</span>
	</section>
	
	<section data-e="subb" data-x data-gm-acte="F" data-m-tabb="markup">
		<a href="../../../../../en/markup/manual/html.html">HTML manual</a>
		<a href="../../../../../en/markup/manual/css.html">CSS manual</a>
	</section>
	
	<section data-e="subb" data-x data-gm-acte="F" data-m-tabb="javascript">
		<a href="../../../../../en/javascript/book/prime.html">Prime book</a>
		<a href="../../../../../en/javascript/book/practice.html">Practice book</a>
		<a href="../../../../../en/javascript/book/supreme.html">Supreme book</a>
		<a href="../../../../../en/javascript/manual.html">Manual</a>
	</section>
</nav>									</div>
			</header>
			<main>
				<div data-w="nict/hett">
	<h1>Exceptions within promises in JavaScript</h1>
</div>				<div data-p="cont/pane">
<p>
	Let's now learn how to handle exceptions 
	that happen inside a promise. In the event 
	of such a situation, we must reject the 
	promise using a special reject function, 
	which automatically falls into the second 
	parameter of the promise function:
</p>
<div data-p="bock/pane">
	<code data-w="bock/code" data-lo="high" data-m-lang="javascript">let promise = new Promise(function(resolve, reject) {
	setTimeout(function() {
		...
	}, 3000);
});</code>
</div>
<p>
	Inside the promise function, we must call 
	<code data-gs="comd/c" data-x>resolve</code> if everything went well, 
	or <code data-gs="comd/c" data-x>reject</code> if an exception occurred:
</p>
<div data-p="bock/pane">
	<code data-w="bock/code" data-lo="high" data-m-lang="javascript">let promise = new Promise(function(resolve, reject) {
	setTimeout(function() {
		let isError = false;
		
		if (!isError) {
			resolve([1, 2, 3, 4, 5]);   // a promise data
		} else {
			reject('error in promise'); // your error text
		}
	}, 3000);
});</code>
</div>
<p>
	Then, in the <code data-gs="comd/c" data-x>then</code> method, you must 
	pass not one, but two functions as 
	parameters: the first will work if the 
	promise fired properly (<dfn data-gs="comd/d" data-x>resolved</dfn>), 
	and the second - if it fired with an error 
	(<dfn data-gs="comd/d" data-x>rejected</dfn>):
</p>
<div data-p="bock/pane">
	<code data-w="bock/code" data-lo="high" data-m-lang="javascript">promise.then(
	function(result) {
		console.log(result); // displays a promise result 
	},
	function(error) {
		console.log(error);  // displays an error text
	}
);</code>
</div>
<p>
	As a rule, the above code is written in 
	a more compact way, like this:
</p>
<div data-p="bock/pane">
	<code data-w="bock/code" data-lo="high" data-m-lang="javascript">promise.then(function(result) {
	console.log(result); // displays a promise result 
}, function(error) {
	console.log(error);  // displays an error text
});</code>
</div>
<div data-w="cont/task">
	<p>
		Make an async code that will generate 
		random numbers from <code data-gs="comd/n" data-x>0</code> to 
		<code data-gs="comd/n" data-x>5</code>. Wrap it all in a promise. Let 
		the promise return the result of dividing 
		one by the generated number. Let the 
		promise fail if a division by zero 
		occurs, and succeed in all other cases.
	</p>
</div>
</div>			</main>
				<div data-w="nict/nebr">
					<a href="../../../../../en/javascript/book/supreme/promises/intro.html" data-e="prev" data-x>
				<span data-e="arow" data-x>&larr;</span>
			</a>
							<a href="../../../../../en/javascript/book/supreme/promises/error-object.html" data-e="next" data-x>
				<span data-e="arow" data-x>&rarr;</span>
			</a>
			</div>
			<footer data-w="ruct/foot">
				<div data-w="nict/finf">
	<span data-e="text" data-x>
		Trepachev Dmitry &copy; 2012-2024	</span>
	<br>
	<a data-e="link" data-x href="https://t.me/trepachev_dmitry">t.me/trepachev_dmitry</a>
</div>							</footer>
			<div data-w="nict/jump">
	<a href="#top"><span>&uarr;</span></a>
</div>			<div data-w="nict/lagr">
	<a href="../../../../../en/javascript/book/supreme/promises/exceptions.html" data-m-curr="T">en</a><a href="../../../../../ru/javascript/book/supreme/promises/exceptions.html" data-m-curr="F">ru</a></div>					</div>
		
		<script src="../../../../../tore/@/metrikaΣ.js?v=1"></script>	</body>
</html>